export const TAX_DASHBOARD = {
  TITLE: "BÚSQUEDA POR ESPECIE",
  NOT_FOUND: "404: Especies No Encontradas",
  PAGE_RANGE_DISPLAYED: 2,
  MARGIN_RANGE_DISPLAYED: 1,
  ITEMS_PER_PAGE: 12,
  INITIAL_PAGE: 0
}